package com.myapp.springwork.student;


//P9 adding students to the db

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.LocalDate;
import java.time.Month;
import java.util.List;

import static java.time.Month.*;

@Configuration
public class StudentConfig {

    // add Bean
        // inject the student repo, name it repository
    // P10 remove hard coded age
    @Bean
    CommandLineRunner commandLineRunner(StudentRepository repository) {
        return arg -> {
            // remove the id bc it is autogenerated
            Student jordy = new Student(
                    "Jordy",
                    "jordy.demo@demo.com",
                    LocalDate.of(1994, MARCH, 21)
            );

            Student maxine = new Student(
                    "Maxine",
                    "maxine.demo@demo.com",
                    LocalDate.of(2000, JUNE, 24)
            );

            // save the students to the db
                // invoke the repo, use saveAll(), pass students to the List.of()
                // restart the server
            repository.saveAll(
                List.of(jordy, maxine)
            );
        };
    }
}
